### PR TITLE
feat: enable fat link time optimization

### PR DESCRIPTION
**Pull request by trusch**
## fixes KILTProtocol/ticket#1855

This enables link time optimizations in release builds.

## How to test:
Please provide a brief step-by-step instruction.
If necessary provide information about dependencies (specific configuration, branches, database dumps, etc.)

- Step 1
- Step 2
- etc.

## Checklist:

- [ ] I have verified that the code works
  - [ ] No panics! (checked arithmetic ops, no indexing `array[3]` use `get(3)`, ...)
- [ ] I have verified that the code is easy to understand
  - [ ] If not, I have left a well-balanced amount of inline comments
- [ ] I have [left the code in a better state](https://deviq.com/principles/boy-scout-rule)
- [ ] I have documented the changes (where applicable)

### CODE REVIEW

**Comment by trusch** [comment]
/cmd queue -v RUST_LOG=debug -c bench-bot $ runtime spiritnet did

**Comment by trusch** [comment]
/cmd queue -v RUST_LOG=debug -c bench-bot $ runtime peregrine did

**Comment by trusch** [comment]
/cmd queue -v RUST_LOG=debug -c bench-bot $ runtime peregrine *

**Comment by trusch** [comment]
/cmd queue -v RUST_LOG=debug -c bench-bot $ runtime peregrine '*'

**Comment by trusch** [comment]
/cmd queue -v RUST_LOG=debug -c bench-bot $ runtime peregrine "*"

**Comment by ggera** [comment]
/cmd queue -v RUST_LOG=debug -c bench-bot $ runtime spiritnet did

**Comment by ggera** [comment]
/cmd queue -v RUST_LOG=debug -c bench-bot $ runtime spiritnet did

**Comment by trusch** [comment]
/cmd queue -v RUST_LOG=debug -c bench-bot $ runtime spiritnet did

**Comment by trusch** [comment]
/cmd queue -v RUST_LOG=debug -c bench-runtime $ spiritnet

**Comment by trusch** [comment]
/cmd queue -v RUST_LOG=debug -c bench-bot $ spiritnet

**Comment by trusch** [comment]
/cmd queue -v RUST_LOG=debug -c bench-bot $ peregrine

**Review by ntn-x2 — APPROVED** [review]
Nothing relevant for the WASM final size, but definitely nice weight improvements 😁

**Review by weichweich — APPROVED** [review]
love it!

**Pull request merged**
