### PR TITLE
docs: Bring docs changes into DIP read me files

### PR DESCRIPTION
**Pull request by ChrisChinchilla**
## fixes KILTProtocol/ticket#2976

Docs: Tweaks some grammar and readability to the DIP pallet readmes so they can be included in docs.

### CODE REVIEW

**Review by ntn-x2 — COMMENTED** [review]
Looks good! These changes would be applied to `develop`, which is ok, but we branched off for the upcoming release and `develop` will soon have changes that will diverge from the release content. How is that taken into account in the docs? Does it pull the READMEs from a specific branch/tag? In that case, we will need to cherry pick these changes onto the release branch as well.

**Comment by ntn-x2** [comment]
Also please update the PR title to follow conventional commits (the CI fails due to that): https://www.conventionalcommits.org/en/v1.0.0/.
This is probably a `docs:` PR.

**Comment by ChrisChinchilla** [comment]
@ntn-x2 At the moment, the plugin, which I have added here https://github.com/KILTprotocol/docs/pull/291 just pulls a raw file, but I think I can change the URL to be branches of tags instead. However, we need to setup versioning in the docs too to support this, which is tracked in https://github.com/KILTprotocol/ticket/issues/3149 so for now it will have to just be "develop", but that can change… soon ™️ . Short term not ideal, but I think we can track it manually until then.

**Comment by ntn-x2** [comment]
Mhhh then I'd rather have the docs point to the release branch than to develop. I'm saying this because there'll soon be few PRs which make the docs outdated.

**Comment by ChrisChinchilla** [comment]
@ntn-x2 Release 1.12.1?

**Comment by ChrisChinchilla** [comment]
@ntn-x2 OK, done! I'll now fix up the other end.

**Comment by ntn-x2** [comment]
@Ad96el @weichweich do you think we can merge this commit on the release branch and then cherry-pick it on `develop`? I am not sure if the changed README changes the metadata of the WASM, since it's used as the crate top-level documentation as well.

**Comment by ntn-x2** [comment]
@ChrisChinchilla can you check if anything needs to be updated, and then we can merge this?

**Comment by ChrisChinchilla** [comment]
@ntn-x2 Oh! i thought it already was! Nothing has changed that affects this PR, no.

**Pull request merged**
