### PR TITLE
chore: update RILT chain spec and boot nodes

### PR DESCRIPTION
**Pull request by Ad96el**
## fixes KILTProtocol/ticket#3400

RILT is booted from scratch, resulting in a different genesis state/wasm. To add more nodes later on, we need to update the chain's specifications.

The chain spec is generated by calling: 

`docker run kiltprotocol/kilt-node:1.13.0 build-spec --chain=rilt-new --raw > nodes/parachain/res/rilt.json`

The deprecated bootnodes are also updated.

### CODE REVIEW

**Review by ntn-x2 — APPROVED** [review]

**Review by ntn-x2 — CHANGES_REQUESTED** [review]
Let's wait to merge this until after we merge https://github.com/KILTprotocol/kilt-node/pull/643.

**Comment by ntn-x2** [comment]
@Ad96el can you pick this up now and update accordingly? I think it's also a nice exercise to get familiar with the new structure.

**Comment by Ad96el** [comment]
In order to get the chain spec, I did: 

- calculate wasm by `docker run kiltprotocol/kilt-node:1.13.0 export-genesis-wasm --chain=rilt-new > ril_new_wasm.hex`   
- calculate plain chain spec by `./target/debug/kilt-parachain build-spec --chain=rilt-new  > plain.json`
    -  replaced the wasm blob from the plain.json with the wasm blob from the docker image 
    - changed genesis state by:
<details> 
```
 "balances": {
        "balances": [
          [
            "5EUAKn69gCkR97BMK1HssmS2YMDo884VUTNVXyRdkTibPg1n",
            10000000000000000000000
          ],
          [
            "5Ek75jyeVzfxpR5uWnGnEo1AnqKqhU68HrmyoHgPzEU4X9C7",
            10000000000000000000000
          ]
        ]
      },
      "sudo": {
        "key": "5EUAKn69gCkR97BMK1HssmS2YMDo884VUTNVXyRdkTibPg1n"
      },
      "aura": {
        "authorities": []
      },
      "session": {
        "keys": [
          [
            "5EUAKn69gCkR97BMK1HssmS2YMDo884VUTNVXyRdkTibPg1n",
            "5EUAKn69gCkR97BMK1HssmS2YMDo884VUTNVXyRdkTibPg1n",
            {
              "aura": "5EPTCZ2zNNf3YGEFH59aEiEYKLvp1L9Xagx6fKnm97nuk5Aj"
            }
          ],
          [
            "5Ek75jyeVzfxpR5uWnGnEo1AnqKqhU68HrmyoHgPzEU4X9C7",
            "5Ek75jyeVzfxpR5uWnGnEo1AnqKqhU68HrmyoHgPzEU4X9C7",
            {
              "aura": "5EtbfuPqngDXf8mkxFS4HWw7mtnz1uZyn2GtGseVjtb1rrdQ"
            }
          ]
        ]
      },
      "parachainStaking": {
        "stakers": [
          [
            "5EUAKn69gCkR97BMK1HssmS2YMDo884VUTNVXyRdkTibPg1n",
            null,
            200000000000000000000
          ],
          [
            "5Ek75jyeVzfxpR5uWnGnEo1AnqKqhU68HrmyoHgPzEU4X9C7",
            null,
            200000000000000000000
          ]
        ],
        "inflationConfig": {
          "collator": {
            "max_rate": 400000000000000000,
            "reward_rate": {
              "annual": 100000000000000000,
              "per_block": 38025705376
            }
          },
          "delegator": {
            "max_rate": 100000000000000000,
            "reward_rate": {
              "annual": 80000000000000000,
              "per_block": 30420564301
            }
          }
        },
        "maxCandidateStake": 200000000000000000000
      },
      "auraExt": {},
      "democracy": {},
      "council": {
        "members": []
      },
      "technicalCommittee": {
        "members": []
      },
      "technicalMembership": {
        "members": []
      },
      "treasury": {},
      "vesting": {
        "vesting": []
      },
      "tipsMembership": {
        "members": []
      },
      "didLookup": {
        "links": []
      },
      "parachainSystem": {},
      "parachainInfo": {
        "parachainId": 8310
      },
      "polkadotXcm": {
        "safeXcmVersion": 3
      }
```
</details>

-  The raw chain spec is calculated by `./target/debug/kilt-parachain build-spec --chain ./plain.json --raw > peregrine-rilt.json`

**Review by ntn-x2 — COMMENTED** [review]
I don't think we need a new module. The `peregrine-new` generator generates a chainspec that is supposed to be changed locally, as long as the runtime stays the same. So we don't need a `rilt-new` nor the `rilt` module, but simply generate a new chainspec, make any changes locally, generate the raw spec, and paste that into the file tree to be used as `rilt`.

**Review by ntn-x2 — APPROVED** [review]
If the chainspec is the one currently running, let's merge this 🚀

**Comment by ntn-x2** [comment]
Integration tests will be fixed in a separate PR.

**Pull request merged**
